services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: pretty-cake-db
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgrescake
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    container_name: minio_storage
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
  rabbitmq:
    image: 'rabbitmq:latest'  
    container_name: rabbitmq_queue  
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'

    ports:  
      - '5672:5672'

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_backend
    depends_on:
      - db
      - minio
      - rabbitmq
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://db:5432/pretty-cake-db}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME:-postgre}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD:-postgrescake}
      
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-http://minio:9000}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin123}
      
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY:-myaccesskey}
      AWS_SECRET_ACCESS: ${AWS_SECRET_ACCESS:-mysecretkey}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-mytoken}
      
      JWT_SECRET: ${JWT_SECRET:-7Z4/ixOoIRj48XHPDdY2FIXEWLUWHYl7UU9lmVDlhzo=}

      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-secret}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-myuser}
      RABBITMQ_HOST: ${RABBITMQ_HOST:-rabbitmq}

      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - api      
          

volumes:
  postgres_data:
  minio_data: