
# --- MINIO CONFIGURATION
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin123}
minio.bucket.name=cloud-ufc-bucket2

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_DEFAULT_USER:myuser}
spring.rabbitmq.password=${RABBITMQ_DEFAULT_PASS:secret}
queue.name=pretty-queue


spring.devtools.restart.enabled=false
