
spring.application.name=backend-worker


server.port=0
spring.main.web-application-type=none


spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/pretty-cake-db}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:postgrescake}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=false


# Enable RabbitMQ listener in worker profile
spring.rabbitmq.listener.auto-startup=true
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=10

spring.devtools.restart.enabled=false
